// This file is auto-generated by Firebase Studio.
// You can get this config from the Firebase console.
export const firebaseConfig = {
  "projectId": "studio-8961120384-6e1e1",
  "appId": "1:692007016271:web:e6043ed55b2a0d9335573a",
  "apiKey": "AIzaSyD6r2P24m0oaytsM3cOpbtPTgKN83m8JqU",
  "authDomain": "studio-8961120384-6e1e1.firebaseapp.com",
  "measurementId": "",
  "messagingSenderId": "692007016271"
};
